TiCatch/Frontend

- ticatch-front/api/auth.ts
- ticatch-front/api/index.ts
- ticatch-front/app/auth/AuthPageClient.tsx
- ticatch-front/app/auth/page.tsx
- ticatch-front/app/login/page.tsx
- ticatch-front/lib/axiosClient.ts
- ticatch-front/lib/index.ts
- ticatch-front/package-lock.json
- ticatch-front/package.json
- ticatch-front/types/auth.ts
- ticatch-front/types/index.ts
카카오 소셜 로그인 기능 추
- `app/login/page.tsx`: `로그인` 클릭하면 카카오 소셜 로그인 페이지(`KAKAO_AUTH_URL`)로 이동 할 수 있도록 구현
- `types/auth.ts`: `LoginResponse` 타입 추가 (+ `TokenDto` 타입) 백에서 res로 보여주는 데이터 구조 [카카오 로그인 API 명세](https://www.notion.so/193c24ac3ee74ebd9163db1dc48593da)
- `axiosClient.ts`: axiosClient 추가 후 모든 요청에 헤더에 `accessToken` 넣어주는 interceptor 추가
- 헤더에 넣어줄 때는 "Bearer" 추가, localStorage에 넣어줄 때는 "Bearer" 떼고 넣어주기
- `api/auth.ts`: 백엔드에 로그인 요청하는 `loginWithKakao` 추가
- `app/auth/page.tsx`: 로그인 처리 중에 보여지는 화면. 성공하면 루트 페이지로, 실패하면 로그인 페이지로 이동
폴더 구조 괜찮을지 확인 부탁드립니다!
---
> feat: 카카오 소셜 로그인 기능 구현

- ticatch-front/app/(with-header)/ticket/time/page.tsx
useSearchParams로 인한 빌드에러 수정
timepage에 suspense 추가
빌드 정상동작하는지 확인부탁드립니다!
---
> fix: useSearchParams 관련 빌드 에러 수정

- ticatch-front/app/login/page.tsx
KAKAO_AUTH_URL을 http -> https로 수정
기태 유정은 다 되는데 제 노트북에서만 갑자기 카카오 로그인 페이지로 이동이 안돼서 확인해보니 `http`로 되어있어서 수정했습니당 ㅜㅜ
---
> fix: kakao auth url 수정

- ticatch-front/app/globals.css
- ticatch-front/app/page.tsx
- ticatch-front/tailwind.config.ts
홈페이지 구현
- `global.css`: 내부 그림자 속성 값 추가
- `tailwind.config.css`: 내부 그림자 속성 추가, 좌석 질감 표현 반짝이는 효과와 글씨가 4초 뒤에 나타나는 효과 위한 keyframe과 애니메이션 속성 추가
- `app/page.tsx`: 홈 페이지 구현 (로고 + 버튼 + 호버 시 화면으로 보라색 확산 효과 + 호버 또는 4초 뒤에 나타나는 글씨 "좌석을 클릭하세요!"
- 원래 로고를 클릭하면 홈 화면으로 이동하는 것으로 생각했었는데 구현하고 보니까 사실 이미 홈 화면이라서 별로 의미가 없는 것 같더라구요... 그냥 버튼 말고 이미지로만 두는 것이 좋을까요??
---
> feat: 홈페이지 구현

- ticatch-front/api/ticket.ts
- ticatch-front/app/(with-header)/ticket/[ticketingId]/page.tsx
- ticatch-front/components/Modal/CancelModal.tsx
- ticatch-front/components/Modal/CommonModal.tsx
- ticatch-front/utils/getRemainingTime.ts
티켓팅 취소하기 기능 추가
- 티켓 취소 모달추가
- 티켓팅 취소 api 연동
- 취소 후 home으로 redirect
- 티켓 status CANCELED page 접근시, 홈으로 redirect
모달로 처리해놓은것이 괜찮은지 확인부탁드립니다!
---
> Feat: cancel ticketing

- ticatch-front/api/auth.server.ts
refresh token 찾지 못하는 이슈 수정
`refreshToken` -> `refresh-token`
---
> fix: refresh token 찾지 못하는 이슈 수정

- ticatch-front/api/virtual.ts
- ticatch-front/app/api/ticket/waiting/[ticketingId]/[userType]/route.ts
- ticatch-front/middleware.ts
- ticatch-front/vercel.json
api route에서 params 오류 문제 수정
- `middleware.ts`에서 `refresh-token` 수정
- `context.params` 타입 우회
- `vercel.json`에 api 경로 명시
- 가상유저 대기열 진입 요청 재귀적으로 수정
[노션 트러블슈팅 문서 추가](https://www.notion.so/Next-js-15-context-params-Promise-any-1ab9f17661f3804cb1b4cf704ff5c735)
---
> fix: api route에서 params 오류 문제 수정

- ticatch-front/api/index.ts
- ticatch-front/api/payment.ts
- ticatch-front/api/seats.ts
- ticatch-front/api/ticket.ts
- ticatch-front/app/(with-header)/ticket/[ticketingId]/page.tsx
- ticatch-front/app/(with-header)/ticket/[ticketingId]/ticketing/[sectionId]/page.tsx
- ticatch-front/app/(with-header)/ticket/[ticketingId]/ticketing/payment/page.tsx
- ticatch-front/app/(with-header)/ticket/complete/page.tsx
- ticatch-front/app/order/pay/completed/page.tsx
- ticatch-front/middleware.ts
- ticatch-front/types/ticket.ts
선점된 좌석 처리 및 결제 구현
- 선점된 좌석 disabled
- 카카오페이 결제
카카오페이 테스트 결제 잘이루어지는지 확인부탁드립니다 ..!
---
> Feat: reserved seats

- ticatch-front/app/order/pay/completed/PaymentPageClient.tsx
- ticatch-front/app/order/pay/completed/page.tsx
빌드 오류 해결
카카오 결제 페이지 서버컴포넌트, 클라이언트컴포넌트 분리
---
> fix: 결제 page 빌드 오류 해결

- ticatch-front/api/auth.ts
- ticatch-front/app/api/proxy/[...path]/route.ts
- ticatch-front/app/login/page.tsx
- ticatch-front/components/Header.tsx
- ticatch-front/hooks/auth.ts
- ticatch-front/lib/axiosClient.ts
로그인 및 재발급 로직 수정
- 재발급 안되는 이슈 해결 (api method 및 response 수정)
- 로그인 관련 로직 리팩토링
---
> fix: 로그인 및 재발급 로직 수정

- ticatch-front/app/globals.css
- ticatch-front/components/Modal/CommonModal.tsx
- ticatch-front/components/button/CommonButton.tsx
- 공통 모달 버튼 조건부 렌더링 가능하도록 수정
- 공통 모달 스타일 수정
- 공통 버튼 스타일 수정
- 공통 버튼 호버 시 오버레이 효과 추가
- 공통 버튼 크기 수정
- 공통 모달 스타일 수정
- 공통 모달 취소 버튼(+ 엑스 버튼) 조건부로 나타나도록 수정
| 변경 전 | 변경 후|
| ----- | ----- |
| ![image](https://github.com/user-attachments/assets/e4dc3d94-95ed-4c6a-baa2-ef7fd65e3b35)| ![image](https://github.com/user-attachments/assets/c296709e-588a-45b5-a89a-44ba4cbba46c)|
| ![image](https://github.com/user-attachments/assets/28365a96-4d8d-4c34-ad28-3ff8c9c8d4ce) | ![image](https://github.com/user-attachments/assets/096e1e92-430c-491b-b622-f86e1768b5f4) |
---
> style: 공통 모달과 버튼 스타일 수정

- ticatch-front/app/(with-header)/ticket/[ticketingId]/ticketing/[sectionId]/page.tsx
- ticatch-front/app/(with-header)/ticket/complete/page.tsx
- ticatch-front/package.json
- ticatch-front/pnpm-lock.yaml
- ticatch-front/utils/convertSVG.js
- figma svg파일 id -> class 변경 함수
- 좌석 이미지 수정
- 이미 선점된 좌석 선택 시 좌석정보 재호출
- 티켓팅 완료 후 lottie애니메이션 로딩 시 스켈레톤 ui 추가
- convertSVG.js
- S3 이미지
- 좌석호출 함수 callback으로 변경
---
> Fix: seat imgs

- ticatch-front/app/order/pay/completed/PaymentPageClient.tsx
- ticatch-front/components/Modal/TicketingGuard.tsx
- ticatch-front/hooks/ticket.ts
티켓팅 성공 고려 모달 조건 수정
- 티켓팅 성공시에도 진행중인 티켓팅 정보 업데이트
- 결제 로딩 페이지에서 모달 뜨지 않도록 수정
---
> fix: 티켓팅 성공 고려 모달 조건 수정

- ticatch-front/app/(with-header)/ticket/[ticketingId]/page.tsx
- ticatch-front/app/order/pay/completed/PaymentPageClient.tsx
- 결제 오류 수정
- successTicket 위치 수정
- 티켓팅 완료 후 complete page로 넘어갔는데도 티켓팅가드 모달이 자꾸 떠서 successTicket 위치를 변경하였습니다!
---
> Fix: payment ticketing guard

- ticatch-front/lib/axiosClient.ts
재발급 조건 수정
reissue 요청이 안되고 있어서 토큰 만료 에러 코드에 430, 431 추가했습니다. 
---
> fix: 토큰 재발급 상태 코드 추가

- ticatch-front/components/Header.tsx
헤더 z-index 수정 및 backdrop blur 효과 적용
헤더 z-index 수정 및 backdrop blur 효과 적용
- backdrop 효과 위해 오버레이 적용
---
> fix: 헤더 z-index 수정 및 backdrop blur 효과 적용

- ticatch-front/app/(with-header)/ticket/[ticketingId]/page.tsx
- ticatch-front/app/(with-header)/ticket/[ticketingId]/ticketing/waiting/page.tsx
- ticatch-front/app/api/ticket/waiting/[ticketingId]/[userType]/route.ts
가상 유저 요청 재귀적으로 실행되지 않는 이슈 해결
- 가상유저 티켓팅 요청 재귀적으로 수정
- 새 창 한개씩만 띄우도록 수정
- 가상유저 티켓팅 변수 수정
- 대기열 남은 사람 수 증산하여 보여주도록 수정
- 대기열 페이지 반응형 대응
---
> fix: 가상 유저 요청 재귀적으로 실행되지 않는 이슈 해결

- ticatch-front/app/(with-header)/ticket/[ticketingId]/page.tsx
- ticatch-front/components/ticketInfo/LevelCard.tsx
티켓팅 예약/예매 중복 방지
- 티켓팅 예약 더블클릭 방지
- 티켓팅 예매 더블클릭 방지
- 티켓팅 예약 중복 생성 방지
---
> fix: 티켓팅 예약/예매 중복 방지

- ticatch-front/app/(with-header)/ticket/complete/page.tsx
- ticatch-front/app/order/pay/completed/PaymentPageClient.tsx
로컬스토리지 clear 코드 이동
complete page로 이동시 로컬스토리지 정리
---
> fix: complete시 localStorage정리

- ticatch-front/api/seats.ts
- ticatch-front/app/(with-header)/ticket/[ticketingId]/ticketing/[sectionId]/page.tsx
- ticatch-front/app/(with-header)/ticket/[ticketingId]/ticketing/payment/page.tsx
- ticatch-front/app/(with-header)/ticket/[ticketingId]/ticketing/section/page.tsx
- ticatch-front/app/loading.tsx
- ticatch-front/utils/fetchSVG.ts
- ticatch-front/utils/selectTotalSVG.ts
미니좌석도 및 잔여석 리스트
- 미니좌석도 추가 (클릭 시 구역변경)
- 잔여석 api 및 리스트 추가 (클릭 시 구역변경)
- 좌석선택 page 전체 padding 수정
---
> Feat:totalsection in detail

- ticatch-front/app/(with-header)/ticket/[ticketingId]/ticketing/TicketingContext.tsx
- ticatch-front/app/(with-header)/ticket/[ticketingId]/ticketing/layout.tsx
- ticatch-front/app/(with-header)/ticket/[ticketingId]/ticketing/payment/page.tsx
- ticatch-front/app/(with-header)/ticket/[ticketingId]/ticketing/section/page.tsx
- ticatch-front/app/(with-header)/ticket/[ticketingId]/ticketing/waiting/page.tsx
- ticatch-front/constants/ticketingInfo.ts
티켓팅 context 적용 및 결제 page ui 수정
- 티켓팅 page context 추가
- 레벨별 공연제목, 이미지 적용
- 구역별 가격 적용
- 결제 ui overflow 수정
---
> Fix: payment UI
